### ISSUE TITLE
package should be published on npm!

### ISSUE THREAD

**Issue by gswalden** [usermindinc/node-marketo#9]
https://www.npmjs.com/package/node-marketo is empty and waiting.

**Comment by peaches** [comment]
We'll take that into consideration, this needs to be fleshed out a little more before it would make sense to publish on npm.

**Comment by gswalden** [comment]
Gotcha, I'm going to migrate our PHP-based system to a microservice using your library, I'll be sure to submit pull requests if i run into/fix any issues.
